1 Perform the following operations using Python on the Facebook metrics data sets
"\n"a. Create data subsets
"\n"b. Merge Data
"\n"c. Sort Data
"\n"d. Transposing Data
"\n"e. Shape and reshape Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("dataset_Facebook.csv",delimiter = ";")

In [3]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [10]:
# data subsets
# selecting only first 250 rows 
df1 = df.iloc[0:250,:]
df2 = df.iloc[250:500,:]

In [9]:
df1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,130791,Photo,1,7,2,13,0.0,44464,66824,1052,930,1571,22904,14080,559,4,154.0,30.0,188
246,130791,Photo,2,7,2,8,0.0,2881,5188,550,503,730,3840,2040,323,0,73.0,15.0,88
247,129600,Photo,2,7,1,12,0.0,3460,6503,541,482,667,4371,2260,314,0,96.0,19.0,115
248,129600,Photo,3,7,1,6,0.0,3406,5656,571,512,731,4446,2598,355,1,98.0,19.0,118
249,129600,Photo,2,7,7,11,1.0,2602,4349,479,444,588,3342,1946,287,1,53.0,14.0,68

In [11]:
df2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
250,129600,Photo,1,7,7,6,1.0,5848,9068,622,570,795,6651,4212,383,4,71.0,10.0,85
251,129600,Photo,1,7,6,11,0.0,26944,43464,877,740,1097,20270,10208,563,6,194.0,34.0,234
252,129600,Photo,3,7,6,5,0.0,5292,9321,756,646,1033,5867,3404,516,6,226.0,42.0,274
253,129600,Status,2,7,5,12,1.0,15576,27513,2417,2327,3098,19078,10840,1839,11,238.0,51.0,300
254,129600,Photo,3,7,5,3,0.0,54256,82011,1620,963,1419,42128,24224,977,10,755.0,58.0,823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [13]:
# combining data subsets
new_df = pd.concat([df1,df2])

In [14]:
new_df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [22]:
# sorting the dataset based on month
df.sort_values(by=["Post Month"],ascending=True)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119
475,86909,Photo,3,1,6,16,1.0,5754,9238,1179,1143,1452,6101,3546,420,0,65.0,19.0,84
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
478,86909,Photo,3,1,5,13,0.0,5536,8745,1141,1099,1461,5225,3098,483,1,74.0,31.0,106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
38,138895,Status,2,12,7,9,0.0,17576,33058,5352,5202,6547,23135,11792,4104,11,227.0,31.0,269
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100

In [23]:
# shaping and reshaping data
df.shape

(500, 19)

In [37]:
new_shape = np.reshape(df,[19,500])

In [38]:
for i in new_shape:
    print(i,"\n")

[139441 'Photo' 2 12 4 3 0.0 2752 5091 178 109 159 3078 1640 119 4 79.0
 17.0 100 139441 'Status' 2 12 3 10 0.0 10460 19057 1457 1361 1674 11710
 6112 1108 5 130.0 29.0 164 139441 'Photo' 3 12 3 3 0.0 2413 4373 177 113
 154 2812 1503 132 0 66.0 14.0 80 139441 'Photo' 2 12 2 10 1.0 50128 87991
 2211 790 1119 61027 32048 1386 58 1572.0 147.0 1777 139441 'Photo' 2 12 2
 3 0.0 7244 13594 671 410 580 6228 3200 396 19 325.0 49.0 393 139441
 'Status' 2 12 1 9 0.0 10472 20849 1191 1073 1389 16034 7852 1016 1 152.0
 33.0 186 139441 'Photo' 3 12 1 3 1.0 11692 19479 481 265 364 15432 9328
 379 3 249.0 27.0 279 139441 'Photo' 3 12 7 9 1.0 13720 24137 537 232 305
 19728 11056 422 0 325.0 14.0 339 139441 'Status' 2 12 7 3 0.0 11844 22538
 1530 1407 1692 15220 7912 1250 0 161.0 31.0 192 139441 'Photo' 3 12 6 10
 0.0 4694 8668 280 183 250 4309 2324 199 3 113.0 26.0 142 139441 'Status'
 2 12 5 10 0.0 21744 42334 4258 4100 4540 37849 18952 3798 0 233.0 19.0
 252 139441 'Photo' 2 12 5 10 0.0 3112 5590 208 127 145 3887 2174 165 0
 88.0 18.0 106 139441 'Photo' 2 12 5 10 0.0 2847 5133 193 115 133 3779
 2072 152 0 90.0 14.0 104 139441 'Photo' 2 12 5 3 0.0 2549 4896 249 134
 168 3631 1917 183 5 137.0 10.0 152 138414 'Photo' 2 12 4 5 1.0 22784
 39941 887 337 417 34415 19312 684 2 577.0 20.0 599 138414 'Status' 2 12 3
 10 0.0 10060 19680 1264 1209 1425 17272 8548 1162 4 86.0 18.0 108 138414
 'Photo' 3 12 3 3 0.0 1722 2981 163 123 148 1868 1050 123 2 40.0 12.0 54
 138414 'Photo' 1 12 2 12 1.0 53264 111785 1706 1103 1655 92512 39776 1307
 15 678.0 20.0 713 138414 'Status' 3 12 2 3 0.0 3930 7509 130 86 112 5009
 2410 101 4 54.0 17.0 75 138414 'Photo' 3 12 1 11 0.0 1591 2825 121 88 111
 2116 1161 100 0 34.0 8.0 42 138414 'Photo' 2 12 1 3 0.0 2848 5066 200 142
 184 3561 1963 157 3 66.0 12.0 81 138414 'Photo' 1 12 7 10 0.0 1384 2467
 15 15 20 2196 1172 15 0 0.0 0.0 0 138414 'Link' 1 12 7 10 0.0 3454 6853
 118 104 130 6282 3100 106 0 16.0 2.0 18 138414 'Photo' 3 12 7 3 0.0 2723
 4888 176 118 143 2964 1621 143 0 72.0 24.0 96 138414 'Status' 2 12 6 10
 0.0 8488 15294 1341 1270 1489 9684 5244 995 3 99.0 19.0 121 138458
 'Status' 2 12 6 3 0.0 8284 15104 1521 1462 1711 10266 5372 1200 0 88.0
 18.0 106 138458 'Status' 2 12 5 11]

[0.0 19552 34143 2806 2531 3420 17748 9824 1779 10 412.0 72.0 494 138458
 'Photo' 3 12 5 3 0.0 2478 4306 212 124 149 2612 1443 166 0 100.0 17.0 117
 138895 'Photo' 2 12 5 3 0.0 9560 18264 973 559 885 9217 4748 621 36 523.0
 63.0 622 138895 'Video' 1 12 4 11 1.0 36208 61262 1141 1068 1728 30131
 14112 559 18 143.0 13.0 174 138895 'Photo' 2 12 4 2 0.0 4940 9390 385 306
 501 5860 2930 273 33 107.0 22.0 162 138895 'Photo' 2 12 3 10 0.0 1683
 2929 192 171 221 1585 858 131 1 27.0 11.0 39 138895 'Photo' 3 12 3 3 0.0
 5280 9578 368 237 345 4480 2422 268 2 155.0 47.0 204 138895 'Photo' 3 12
 2 9 0.0 3002 5318 268 185 247 3039 1676 194 4 98.0 23.0 125 138895
 'Photo' 1 12 2 3 0.0 3766 7149 298 260 431 5782 2938 244 2 56.0 17.0 75
 138895 'Photo' 2 12 1 11 0.0 4512 7808 423 284 431 5183 2954 316 6 172.0
 21.0 199 138895 'Photo' 3 12 1 3 0.0 2690 4628 252 168 226 3052 1727 199
 0 96.0 17.0 113 138895 'Photo' 1 12 7 10 1.0 19800 28663 479 424 805 5187
 2752 248 16 76.0 8.0 100 138895 'Status' 2 12 7 9 0.0 17576 33058 5352
 5202 6547 23135 11792 4104 11 227.0 31.0 269 138895 'Photo' 1 12 7 3 0.0
 3290 6085 306 284 402 4986 2584 247 1 44.0 14.0 59 138895 'Status' 2 12 6
 11 0.0 13280 24198 2055 1912 2720 17627 9344 1716 7 216.0 39.0 262 138895
 'Link' 1 12 6 3 1.0 18480 28438 517 366 460 12078 6752 319 6 187.0 18.0
 211 138353 'Photo' 1 12 5 10 0.0 7268 13989 2087 2079 12074 13544 7096
 1975 7 26.0 3.0 36 138353 'Link' 1 12 5 3 1.0 2645 4270 134 109 170 2330
 1377 101 7 29.0 10.0 46 138353 'Photo' 1 12 4 11 0.0 4284 8387 355 316
 513 7283 3634 291 0 47.0 11.0 58 138353 'Link' 1 12 4 3 1.0 7968 13023
 206 158 223 6734 3492 138 4 57.0 10.0 71 138353 'Status' 1 12 3 11 0.0
 16576 30612 3572 3464 4802 24363 12888 3014 4 174.0 36.0 214 138353
 'Link' 1 12 3 2 0.0 1925 3481 97 83 126 2307 1180 77 6 18.0 8.0 32 138353
 'Photo' 1 12 2 11 0.0 3786 7329 338 283 450 6336 3216 280 0 77.0 15.0 92
 138353 'Link' 1 12 2 2 0.0 1536 3094 84 76 99 2903 1407 76 1 12.0 1.0 14
 138353 'Photo' 2 11 1 9 0.0 1728 3155 108 65 95 2313 1232 77 1 48.0 9.0
 58 138329 'Photo' 1 11 1 3 1.0 25248 40125 726 467 863 16132 8608 451 24
 285.0 28.0 337 138329 'Photo' 1 11 7 9 0.0 4894 8899 355 181 264]

[4914 2712 246 9 202.0 31.0 242 138329 'Photo' 1 11 7 3 0.0 2935 5439 237
 182 401 3901 2044 201 4 64.0 19.0 87 138329 'Photo' 1 11 6 10 0.0 2425
 4462 260 213 433 3017 1510 175 4 66.0 13.0 83 138329 'Video' 1 11 6 2 1.0
 16416 31950 459 411 539 21436 9568 363 2 65.0 14.0 81 138329 'Photo' 1 11
 5 11 0.0 5812 10465 343 204 301 4976 2764 240 2 164.0 54.0 220 138329
 'Photo' 1 11 5 3 0.0 2545 4846 165 131 167 3675 1901 134 0 40.0 13.0 53
 138329 'Photo' 1 11 4 10 0.0 2257 4372 230 173 327 3188 1557 168 3 76.0
 11.0 90 138329 'Photo' 1 11 4 3 1.0 27072 84885 421 304 487 35637 9712
 263 4 139.0 17.0 160 138185 'Photo' 1 11 3 11 1.0 10940 27951 417 335 591
 15066 5100 319 8 101.0 14.0 123 138185 'Photo' 1 11 3 2 1.0 50912 164528
 630 513 952 54653 12704 346 8 144.0 10.0 162 138185 'Photo' 1 11 2 10 1.0
 28752 47358 802 654 1268 14091 7456 408 10 179.0 13.0 202 138185 'Photo'
 1 11 2 3 1.0 27216 81908 541 335 540 26869 7760 315 4 219.0 22.0 245
 138185 'Photo' 1 11 1 10 0.0 2352 5234 232 182 258 4101 1761 181 2 60.0
 7.0 69 138185 'Photo' 1 11 1 3 0.0 3416 6167 356 298 641 4530 2388 280 19
 77.0 23.0 119 138185 'Photo' 1 11 7 11 0.0 2149 4120 197 156 219 3302
 1640 161 0 48.0 7.0 55 138185 'Photo' 1 11 7 3 1.0 53456 93790 1576 995
 1469 32646 14912 884 20 697.0 70.0 787 138185 'Photo' 1 11 6 11 0.0 2168
 3891 211 168 202 2873 1539 171 0 53.0 17.0 70 137893 'Photo' 1 11 6 3 0.0
 3102 5939 360 288 512 3537 1780 275 7 84.0 28.0 119 137893 'Photo' 1 11 5
 10 1.0 39344 103050 588 460 695 39304 11392 336 7 146.0 9.0 162 137893
 'Video' 1 11 5 3 1.0 100768 220447 2101 1735 2331 59658 18880 885 17
 449.0 84.0 550 137893 'Status' 3 11 4 11 0.0 9056 16362 1006 847 1153
 9562 5180 740 3 226.0 44.0 273 137893 'Photo' 1 11 4 2 1.0 11444 46054
 555 418 717 13737 4320 438 14 172.0 47.0 233 137893 'Video' 1 11 3 11 0.0
 13544 30235 517 458 667 26622 11760 447 2 99.0 13.0 114 137893 'Photo' 1
 11 3 2 1.0 37376 68610 1150 808 1341 22100 10880 724 20 411.0 74.0 505
 137893 'Photo' 1 11 3 2 0.0 1228 2392 17 17 19 2392 1228 17 0 0.0 0.0 0
 137177 'Photo' 1 11 1 10 0.0 22984 59040 438 374 542 12716 4968 262 4
 85.0 8.0 97 137177 'Photo' 2 11 1 3 0.0 1445 2774 217 167 211 1924 1005
 154 0 56.0 8.0]

[64 137177 'Photo' 1 11 7 12 0.0 3754 8533 658 640 2085 6838 3224 598 2
 29.0 7.0 38 137177 'Status' 2 11 7 3 0.0 8728 17827 2295 2235 2828 15418
 7344 2099 2 86.0 13.0 101 137177 'Photo' 3 11 6 10 0.0 5990 11123 657 361
 512 5057 2628 428 18 370.0 53.0 441 137177 'Photo' 1 11 6 3 0.0 4582 9193
 454 306 431 3691 1722 305 5 190.0 57.0 252 137177 'Photo' 3 11 5 10 1.0
 2938 5799 321 243 379 3668 1848 236 2 101.0 19.0 122 137177 'Status' 3 11
 5 2 0.0 6692 13092 199 108 141 7549 3336 156 2 99.0 16.0 117 137177
 'Photo' 1 11 4 9 1.0 2566 5244 384 280 469 3834 1806 266 10 140.0 8.0 158
 137177 'Link' 1 11 4 3 0.0 21176 54779 330 228 329 13858 5248 185 2 130.0
 31.0 163 137177 'Photo' 3 11 3 10 0.0 4012 7955 550 319 477 4625 2218 403
 3 270.0 38.0 311 137177 'Photo' 1 11 3 3 0.0 1531 2838 212 189 1359 1210
 690 143 3 30.0 6.0 39 137059 'Photo' 1 11 2 11 1.0 2938 6056 374 283 483
 4509 2078 287 2 107.0 17.0 126 137059 'Photo' 1 11 2 3 0.0 24720 37240
 845 564 850 14475 8120 504 13 331.0 77.0 421 137059 'Photo' 2 11 1 9 0.0
 2219 4545 287 220 329 3189 1495 221 0 78.0 13.0 91 137059 'Photo' 3 11 1
 3 0.0 4732 9303 607 352 518 6201 3136 445 9 301.0 32.0 342 137059 'Photo'
 3 11 7 9 0.0 2225 4239 310 216 289 2570 1389 233 2 111.0 16.0 129 137059
 'Photo' 2 11 7 4 0.0 2626 4943 316 213 299 3047 1605 244 2 124.0 22.0 148
 137059 'Photo' 3 10 6 10 0.0 3090 5744 391 257 360 3521 1796 293 5 153.0
 27.0 185 137059 'Photo' 1 10 6 3 0.0 1101 2548 324 287 2418 1284 704 220
 3 51.0 11.0 65 137059 'Photo' 2 10 5 11 0.0 2819 5230 318 218 303 3128
 1622 240 1 115.0 26.0 142 137020 'Status' 2 10 5 3 1.0 12468 24917 2143
 1966 2576 15850 7636 1661 7 310.0 61.0 378 137020 'Photo' 1 10 4 10 0.0
 12776 21893 785 539 881 13272 7800 575 12 328.0 90.0 430 137020 'Photo' 1
 10 4 9 1.0 1357 2453 37 37 55 2154 1120 32 0 0.0 0.0 0 137020 'Photo' 2
 10 4 3 0.0 68896 104952 2624 1326 1952 35707 19840 1354 26 1505.0 95.0
 1626 137020 'Photo' 3 10 3 10 0.0 1711 3174 288 245 339 2226 1118 205 2
 63.0 14.0 79 137020 'Photo' 1 10 3 4 0.0 1388 2544 224 219 931 2161 1214
 172 0 13.0 4.0 17 137020 'Photo' 1 10 2 11 1.0 2645 5472 357 315 482 4485
 2101 265 4 59.0 9.0 72 137020 'Photo' 1 10 2]

[4 0.0 70144 111745 3216 2628 4782 43671 20608 1542 42 955.0 139.0 1136
 137020 'Photo' 3 10 1 11 0.0 3674 7221 452 330 487 3832 1890 328 9 181.0
 32.0 222 136736 'Status' 2 10 1 4 0.0 9504 19556 1132 1032 1512 16018
 7616 981 17 193.0 28.0 238 136736 'Photo' 3 10 7 9 0.0 2426 4469 320 237
 325 3120 1684 248 7 125.0 16.0 148 136736 'Status' 2 10 7 3 0.0 13872
 27468 2664 2570 3395 20198 10432 2252 4 217.0 50.0 271 136736 'Photo' 1
 10 6 10 0.0 1673 3655 338 324 1619 2598 1469 268 2 28.0 4.0 34 136736
 'Photo' 1 10 6 8 0.0 1261 2158 37 37 49 1911 1077 33 0 nan nan 0 136736
 'Photo' 2 10 6 4 0.0 2428 4510 311 238 323 2888 1560 236 4 117.0 18.0 139
 136642 'Photo' 2 10 1 3 1.0 2227 4070 369 314 430 3227 1702 306 2 79.0
 16.0 97 136642 'Photo' 1 10 7 13 0.0 1592 2749 370 356 414 2551 1454 327
 0 15.0 2.0 17 136642 'Photo' 1 10 7 12 1.0 813 1568 323 319 387 1402 695
 280 0 4.0 2.0 6 136642 'Photo' 1 10 7 12 0.0 32208 57472 1810 1490 2286
 56149 31648 1724 1 431.0 26.0 458 136642 'Photo' 1 10 7 11 0.0 729 1374
 303 298 331 1284 650 262 0 7.0 0.0 7 136642 'Photo' 1 10 7 10 0.0 834
 1570 399 392 510 1390 704 351 0 7.0 2.0 9 136393 'Photo' 1 10 7 10 0.0
 786 1573 263 257 318 1401 660 222 0 6.0 2.0 8 136393 'Photo' 1 10 7 9 0.0
 584 1029 273 271 308 943 511 232 0 2.0 nan 2 136393 'Status' 2 10 7 9 0.0
 15816 30514 2733 2654 3289 23584 11912 2361 6 186.0 40.0 232 136393
 'Photo' 1 10 7 8 0.0 619 1096 257 254 292 951 516 217 1 1.0 2.0 4 136393
 'Photo' 1 10 7 7 0.0 617 1071 229 223 265 935 521 191 1 3.0 2.0 6 136393
 'Photo' 1 10 7 6 0.0 677 1285 251 246 297 1210 615 211 0 7.0 nan 7 136393
 'Photo' 1 10 7 5 0.0 677 1240 236 228 264 1098 580 196 0 7.0 2.0 9 136393
 'Photo' 3 10 7 3 0.0 3366 6647 474 345 495 3180 1674 385 3 198.0 41.0 242
 136393 'Photo' 1 10 6 13 0.0 747 1443 226 220 287 1252 632 194 0 9.0 1.0
 10 136393 'Photo' 1 10 6 13 0.0 645 1117 195 192 224 989 554 166 0 4.0
 1.0 5 136393 'Photo' 1 10 6 12 0.0 754 1510 206 205 252 1430 690 175 0
 3.0 0.0 3 136393 'Photo' 1 10 6 11 0.0 910 1673 207 201 247 1503 782 176
 0 8.0 2.0 10 136393 'Photo' 1 10 6 9 0.0 3906 8239 868 863]

[2632 7736 3768 774 0 7.0 3.0 10 136393 'Photo' 1 10 6 9 0.0 659 1158 199
 194 239 1041 576 169 1 7.0 2.0 10 136393 'Photo' 1 10 6 8 0.0 652 1331
 214 206 249 1249 588 182 0 11.0 1.0 12 136393 'Photo' 1 10 6 6 0.0 861
 1565 214 192 239 1351 717 180 2 28.0 4.0 34 136393 'Photo' 1 10 6 2 0.0
 3690 7659 424 388 644 6951 3290 377 0 56.0 12.0 68 136393 'Link' 1 10 5
 10 0.0 4664 9463 204 182 251 7196 3324 173 0 32.0 16.0 48 136013 'Photo'
 1 10 5 8 0.0 1080 2427 210 189 249 2195 934 184 4 32.0 3.0 39 136013
 'Status' 2 10 5 3 0.0 8896 17202 1480 1426 1932 13838 7020 1292 0 129.0
 25.0 154 136013 'Photo' 1 10 4 10 1.0 4018 8617 428 374 616 6677 2992 351
 4 77.0 19.0 100 136013 'Link' 1 10 4 3 0.0 68992 229733 1032 975 1345
 17842 8032 635 15 143.0 44.0 202 136013 'Status' 3 10 3 10 0.0 13152
 25666 2543 2438 3179 20547 10280 2278 2 227.0 36.0 265 136013 'Status' 2
 10 3 2 1.0 31136 59964 6164 5934 9237 35977 18048 4376 60 859.0 90.0 1009
 136013 'Photo' 3 10 2 10 1.0 16776 39549 714 440 720 11860 6200 590 10
 377.0 60.0 447 136013 'Photo' 1 10 2 3 1.0 50736 140432 1462 1450 8308
 46252 15552 1275 3 41.0 9.0 53 136013 'Photo' 1 10 1 10 1.0 5324 11040
 528 483 861 8627 4054 448 6 76.0 14.0 96 136013 'Photo' 3 10 1 3 0.0
 18120 44940 421 282 463 4401 2616 327 0 189.0 15.0 204 135713 'Photo' 3
 10 7 10 0.0 2291 3960 303 243 325 3020 1723 253 0 80.0 14.0 94 135713
 'Status' 2 10 7 4 0.0 10744 20691 1967 1877 2201 17502 8964 1834 3 148.0
 28.0 179 135713 'Link' 1 10 6 11 1.0 3616 6887 111 90 118 4263 2138 93 0
 24.0 11.0 35 135713 'Photo' 1 10 6 4 0.0 39984 112830 2105 1921 3932
 70249 21328 1609 24 302.0 41.0 367 135713 'Photo' 2 10 5 11 0.0 4010 7444
 477 370 534 4406 2362 354 2 166.0 32.0 200 135713 'Photo' 2 10 5 4 1.0
 6564 12097 806 602 957 7682 4024 563 47 358.0 49.0 454 135713 'Photo' 1
 10 4 10 0.0 8612 20151 813 727 1390 16890 7208 630 7 161.0 25.0 193
 135713 'Photo' 2 10 4 1 0.0 5568 10282 746 545 867 5696 3162 537 13 319.0
 55.0 387 135700 'Photo' 2 9 3 7 0.0 1685 2999 322 295 424 1794 953 237 0
 54.0 16.0 70 135700 'Photo' 2 9 2 11 0.0 3756 7094 469 408 613 4935 2556
 365 16 117.0 30.0 163 135700 'Photo' 3 9 2 2 0.0 2656 4862 390 309 445
 3273 1722 309 1 115.0]

[21.0 137 135700 'Photo' 2 9 1 10 0.0 5086 9493 622 509 757 6200 3298 489
 30 187.0 35.0 252 135617 'Photo' 2 9 1 3 1.0 2055 3915 346 288 412 2970
 1507 277 1 84.0 13.0 98 135617 'Photo' 3 9 7 9 0.0 9384 14948 757 452 652
 11148 7020 604 6 363.0 40.0 409 135617 'Photo' 2 9 7 3 0.0 3992 7255 598
 447 688 4428 2420 435 6 244.0 32.0 282 135617 'Photo' 3 9 6 10 0.0 7512
 13633 769 614 951 5503 3260 530 22 290.0 98.0 410 135617 'Status' 2 9 6 4
 0.0 11096 21080 1843 1724 2106 16095 8120 1604 4 243.0 41.0 288 135428
 'Photo' 1 9 5 10 0.0 1060 2004 266 251 337 1705 870 204 0 18.0 nan 18
 135428 'Photo' 2 9 5 3 1.0 2790 4879 435 360 513 3501 1999 351 0 113.0
 19.0 132 135428 'Photo' 1 9 4 10 1.0 13856 37716 519 450 672 26832 9064
 389 2 77.0 5.0 84 135428 'Photo' 3 9 4 2 1.0 10748 19724 892 498 719
 13674 7624 704 8 485.0 64.0 557 135428 'Photo' 1 9 3 10 0.0 41984 68290
 3370 2420 4074 34802 20928 2126 144 1622.0 208.0 1974 135428 'Photo' 2 9
 3 2 1.0 2522 4583 455 390 547 3031 1674 333 6 99.0 16.0 121 135195
 'Photo' 3 9 2 9 0.0 4480 8039 572 430 599 5014 2704 416 3 188.0 26.0 217
 135195 'Photo' 1 9 2 2 0.0 1543 2874 360 334 463 2373 1228 267 2 30.0 6.0
 38 135195 'Status' 2 9 1 10 0.0 21256 41906 4840 4754 5906 35455 17592
 4318 38 163.0 27.0 228 135195 'Photo' 1 9 1 4 0.0 4484 7829 545 424 629
 4208 2412 382 6 179.0 40.0 225 135195 'Photo' 2 9 7 3 0.0 4398 8105 584
 446 669 4799 2616 431 5 204.0 34.0 243 135195 'Status' 2 9 6 10 1.0 13216
 24738 2675 2584 2969 19599 10232 2342 2 165.0 22.0 189 135195 'Photo' 3 9
 6 3 1.0 22304 37159 1805 984 1618 22864 13304 1349 29 1047.0 98.0 1174
 135195 'Photo' 1 9 5 11 0.0 6208 10830 644 473 678 6866 4016 495 2 234.0
 40.0 276 135195 'Photo' 2 9 5 2 0.0 4518 8533 626 482 729 4215 2254 439 7
 250.0 42.0 299 135195 'Photo' 2 9 4 10 0.0 3582 6518 537 430 597 3857
 2124 404 4 154.0 36.0 194 134879 'Status' 2 9 4 4 1.0 9124 17776 1476
 1397 1797 13887 7092 1331 20 150.0 29.0 199 134879 'Photo' 1 9 3 10 0.0
 14152 38806 631 549 836 19409 6632 404 4 102.0 8.0 114 134879 'Photo' 3 9
 3 2 1.0 4260 7989 588 435 622 4578 2432 436 1 226.0 44.0 271 134879
 'Video' 1 9 2 10 0.0 30624 56950 2080 1956 3253 32033 15744 1376 6 345.0
 121.0 472 134879 'Photo' 2 9]

[2 3 0.0 2363 4223 393 348 476 3332 1788 297 11 68.0 11.0 90 134879
 'Photo' 1 9 1 10 0.0 2232 4005 374 335 458 3247 1740 278 0 62.0 10.0 72
 134879 'Photo' 2 9 1 6 0.0 4048 7217 544 405 602 4046 2280 368 5 223.0
 35.0 263 134879 'Photo' 2 9 7 10 0.0 1804 2968 330 280 352 2293 1354 234
 0 61.0 6.0 67 134879 'Photo' 3 9 7 4 1.0 2351 4028 371 298 392 3112 1791
 288 1 104.0 12.0 117 133679 'Photo' 2 9 2 10 0.0 3100 5388 518 422 609
 3927 2274 367 3 146.0 15.0 164 133679 'Photo' 3 9 2 3 1.0 2360 4004 436
 365 486 2757 1603 300 2 102.0 15.0 119 133679 'Photo' 3 8 1 10 0.0 19648
 33643 1359 695 990 24034 13528 1020 9 766.0 43.0 818 133679 'Photo' 2 8 1
 4 0.0 2295 3721 377 324 402 3121 1882 269 0 63.0 7.0 70 133594 'Photo' 2
 8 7 10 1.0 3934 6330 512 437 599 5010 3082 384 3 113.0 17.0 133 133594
 'Photo' 1 8 7 3 0.0 34512 76659 1666 1333 1977 54860 22816 1278 6 442.0
 42.0 490 133594 'Photo' 2 8 6 10 0.0 5282 8730 703 530 772 5123 3244 470
 9 278.0 43.0 330 133594 'Photo' 1 8 6 8 0.0 1809 3130 399 359 494 2541
 1435 289 2 64.0 7.0 73 133594 'Photo' 2 8 5 13 0.0 1920 3124 365 331 428
 2541 1519 251 1 52.0 7.0 60 133451 'Photo' 1 8 4 9 1.0 1954 3530 356 333
 443 3295 1772 252 0 30.0 2.0 32 132817 'Photo' 3 8 4 10 0.0 33536 64850
 1954 1016 1678 50076 24448 1564 33 1155.0 102.0 1290 132817 'Photo' 2 8 4
 3 1.0 4204 7191 498 408 596 5161 2974 387 2 139.0 25.0 166 132817 'Photo'
 1 8 3 9 0.0 3376 6557 428 409 631 5700 2806 331 0 40.0 5.0 45 132817
 'Status' 2 8 3 2 1.0 9236 16054 1151 1130 1560 14014 7880 1075 2 53.0
 15.0 70 132817 'Photo' 3 8 2 10 0.0 72864 205934 946 759 1158 122474
 30912 646 4 220.0 19.0 243 132817 'Photo' 3 8 2 3 0.0 3358 5682 394 323
 523 4200 2426 298 2 114.0 16.0 132 132201 'Photo' 1 8 1 12 1.0 3254 5644
 371 344 513 5069 2846 283 0 39.0 3.0 42 132201 'Photo' 1 8 1 3 0.0 50640
 121234 2240 1577 2779 92348 34880 1790 4 859.0 68.0 931 132201 'Photo' 2
 8 7 10 0.0 3734 6218 529 434 794 4831 2868 389 5 137.0 20.0 162 132201
 'Photo' 3 8 7 3 0.0 2594 4220 347 315 529 3418 2067 248 1 54.0 11.0 66
 132201 'Photo' 2 8 6 10 1.0 2232 3772 376 322 440 2205 1306 257 2 74.0
 22.0 98 132201 'Photo' 3 8 6 3 1.0 22120 54734 979]

[906 1751 46700 17528 796 6 98.0 3.0 107 132201 'Photo' 3 8 5 10 0.0 7980
 12978 630 398 521 9342 5372 467 2 264.0 21.0 287 132201 'Photo' 2 8 5 1
 0.0 1659 2845 345 321 424 1604 915 239 3 36.0 11.0 50 132201 'Photo' 3 8
 4 11 1.0 1006 1594 277 268 354 1055 651 187 1 11.0 3.0 15 132201 'Photo'
 3 8 4 3 1.0 12728 21685 844 461 683 15779 8844 657 4 435.0 31.0 470
 131956 'Photo' 1 8 3 10 0.0 28880 64746 1062 991 1971 40181 15808 740 2
 114.0 10.0 126 131956 'Photo' 2 8 3 4 0.0 1330 2327 363 351 433 1475 827
 230 2 17.0 9.0 28 131956 'Status' 2 8 2 12 0.0 14424 26000 304 286 383
 25539 14056 291 41 15.0 1.0 57 131956 'Photo' 1 8 2 7 0.0 14200 26728
 1393 1354 3214 25610 13376 1233 3 87.0 10.0 100 131956 'Photo' 3 8 1 12
 0.0 5746 9874 769 632 1063 7407 4288 584 16 227.0 28.0 271 131956 'Photo'
 2 8 1 4 0.0 2540 4372 389 330 458 3655 2063 279 2 86.0 8.0 96 131956
 'Photo' 3 8 7 10 0.0 4324 7241 548 431 676 4972 3008 401 6 179.0 27.0 212
 131808 'Status' 2 8 7 4 0.0 8260 14305 997 953 1211 12905 7360 956 1 74.0
 11.0 86 131808 'Status' 2 8 6 10 1.0 20168 35904 3370 3244 5106 26881
 15056 2806 18 332.0 54.0 404 131808 'Photo' 1 8 6 6 0.0 5046 9084 528 477
 906 7723 4184 421 2 80.0 21.0 103 131808 'Status' 2 7 5 14 0.0 15296
 25269 2827 2781 3627 22103 13296 2602 9 95.0 17.0 121 131728 'Photo' 3 7
 5 8 1.0 3414 6369 473 342 525 4518 2390 360 3 188.0 26.0 217 131728
 'Photo' 1 7 4 10 1.0 95424 252207 699 575 882 78287 22016 417 6 109.0
 11.0 126 131728 'Photo' 2 7 4 3 0.0 14824 21863 868 591 966 13498 8560
 650 64 367.0 25.0 456 131630 'Photo' 2 7 3 13 0.0 3504 5699 444 374 497
 4487 2730 348 9 102.0 19.0 130 131630 'Photo' 3 7 2 23 0.0 2822 5058 424
 351 486 3681 2020 327 2 113.0 20.0 135 131630 'Photo' 3 7 2 13 0.0 2973
 5063 356 297 415 3764 2208 266 0 94.0 20.0 114 131630 'Status' 2 7 2 6
 1.0 10824 20573 135 126 153 20030 10384 126 6 14.0 1.0 21 131630 'Photo'
 1 7 1 11 0.0 4592 6691 320 289 423 3238 2100 222 1 43.0 10.0 54 131630
 'Photo' 2 7 1 5 0.0 3176 5278 372 319 577 3993 2426 279 1 98.0 21.0 120
 131300 'Status' 2 7 7 10 0.0 10956 19279 128 119 130 18838 10564 123 3
 13.0 1.0 17 131300 'Photo' 3 7 7 4 0.0 10888 19744 913 783 1370 14425
 8048 722 12]

[237.0 45.0 294 131300 'Photo' 2 7 6 10 0.0 3594 6316 424 354 530 4319
 2468 309 4 112.0 23.0 139 131300 'Photo' 1 7 6 2 0.0 3384 6166 451 395
 561 4708 2508 344 2 101.0 25.0 128 130791 'Photo' 2 7 5 11 1.0 4096 7200
 487 406 723 4911 2826 355 10 145.0 31.0 186 130791 'Photo' 3 7 5 3 0.0

In [4]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [40]:
# to transpose only certain columns  what we can do 
df6 = df.iloc[:,0:10]
df6

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users
0,139441,Photo,2,12,4,3,0.0,2752,5091,178
1,139441,Status,2,12,3,10,0.0,10460,19057,1457
2,139441,Photo,3,12,3,3,0.0,2413,4373,177
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211
4,139441,Photo,2,12,2,3,0.0,7244,13594,671
...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733
496,81370,Photo,2,1,5,8,0.0,3480,6229,537
497,81370,Photo,1,1,5,2,0.0,3778,7216,625
498,81370,Photo,3,1,4,11,0.0,4156,7564,626
499,81370,Photo,2,1,4,4,NaN,4188,7292,564

In [42]:
df6.transpose()

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564

In [43]:
df7 = df.iloc[:250,0:10]
df7

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users
0,139441,Photo,2,12,4,3,0.0,2752,5091,178
1,139441,Status,2,12,3,10,0.0,10460,19057,1457
2,139441,Photo,3,12,3,3,0.0,2413,4373,177
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211
4,139441,Photo,2,12,2,3,0.0,7244,13594,671
...,...,...,...,...,...,...,...,...,...,...
245,130791,Photo,1,7,2,13,0.0,44464,66824,1052
246,130791,Photo,2,7,2,8,0.0,2881,5188,550
247,129600,Photo,2,7,1,12,0.0,3460,6503,541
248,129600,Photo,3,7,1,6,0.0,3406,5656,571
249,129600,Photo,2,7,7,11,1.0,2602,4349,479

In [44]:
df7.transpose()

,0,1,2,3,4,5,6,7,8,9,...,240,241,242,243,244,245,246,247,248,249
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,130791,130791,130791,130791,130791,130791,130791,129600,129600,129600
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Status,Video,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,1,2,1,2,1,2,2,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,7,7,7,7,7,7,7,7,7,7
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,5,4,4,3,3,2,2,1,1,7
Post Hour,3,10,3,10,3,9,3,9,3,10,...,3,11,6,11,5,13,8,12,6,11
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,19968,4892,17360,21872,180480,44464,2881,3460,3406,2602
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,35161,8499,33613,40413,319133,66824,5188,6503,5656,4349
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,1016,536,2573,3872,8072,1052,550,541,571,479